"""
Django settings for acco project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from environ import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env()
# Phase 1 Hardening: Explicitly load .env from BASE_DIR to ensure boot stability
Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = [
    '127.0.0.1',
    '35.154.23.157',
    'www.accoplacers.com',
    'accoplacers.com',
]

# Required by Django 4.0+ for HTTPS CSRF validation
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8080',
    'http://127.0.0.1',
    'http://35.154.23.157',
    'https://accoplacers.com',
    'https://www.accoplacers.com',
]


# Application definition

INSTALLED_APPS = [
    'base',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'acco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'acco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'emp',
        'HOST': 'localhost',
        'PORT': '3306',
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '')
    }
}

# Fallback to SQLite for local development if MySQL is not available or connection fails
if os.environ.get('DJANGO_LOCAL_SQLITE', 'True') == 'True':
    try:
        import MySQLdb
        # We'll check if we can actually connect. If not, we fall back.
        # This is slightly slow but robust for "booting up" anywhere.
        conn = MySQLdb.connect(
            host=DATABASES['default']['HOST'],
            user=DATABASES['default']['USER'],
            passwd=DATABASES['default']['PASSWORD'],
            db=DATABASES['default']['NAME'],
            port=int(DATABASES['default']['PORT']),
            connect_timeout=1
        )
        conn.close()
    except (ImportError, Exception):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dubai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "base" / "static",  # adjust to your app name
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STRIPE_PUBLIC_KEY = env("STRIPE_PUBLIC_KEY")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")

# File upload size limits (10 MB per file, 15 MB total request)
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024   # 15 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB

# Phase 1: Config Centralization
STRIPE_PLAN_PRICES = {
    'basic': int(env("STRIPE_PRICE_BASIC", default="49")),
    'intermediate': int(env("STRIPE_PRICE_INTERMEDIATE", default="89")),
    'premium': int(env("STRIPE_PRICE_PREMIUM", default="149")),
}

EMPLOYEE_PROFILE_DEPOSIT_AED = int(env("EMPLOYEE_PROFILE_DEPOSIT_AED", default="500"))
EMPLOYEE_PROFILE_REFUND_DAYS = int(env("EMPLOYEE_PROFILE_REFUND_DAYS", default="2"))

WHATSAPP_CONTACT_NUMBER = env("WHATSAPP_NUMBER", default="971589288746")

# Phase 0: Session Hardening
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 hours in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Phase 3: Auth System Hardening
AUTH_USER_MODEL = 'base.UserAccount'

# Phase 4: Admin Hardening
ADMIN_URL = env("DJANGO_ADMIN_URL", default="admin/")
LOGIN_URL = 'admin:login'

# Production Security Hardening
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
