# Generated by Django 5.1.2 on 2026-04-19 13:49

import django.db.models.deletion
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# base.migrations.0013_migrate_skills_data

class Migration(migrations.Migration):

    replaces = [('base', '0001_initial'), ('base', '0002_registration_plan'), ('base', '0003_employer_registration_password_and_more'), ('base', '0004_registration_photo'), ('base', '0005_registration_skills'), ('base', '0008_increase_password_length'), ('base', '0009_registration_is_placed_alter_employer_password_and_more'), ('base', '0010_employerinterest'), ('base', '0011_employeeinterest'), ('base', '0012_skill_registration_skill_tags'), ('base', '0013_migrate_skills_data'), ('base', '0014_remove_registration_skill_tags_and_more'), ('base', '0015_useraccount'), ('base', '0016_useraccount_groups_useraccount_is_superuser_and_more'), ('base', '0017_registration_profile_score')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('company_description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='employer_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary_range', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(default='Full-time', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='base.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('premium', 'Premium')], default='basic', max_length=20)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills (e.g., Excel, Tally, SAP, QuickBooks)', null=True)),
                ('is_placed', models.BooleanField(default=False, help_text='Mark this employee as placed (hired by an employer)')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='base.registration')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='base.employer')),
            ],
            options={
                'unique_together': {('employer', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interests', to='base.registration')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_interests', to='base.jobopening')),
            ],
            options={
                'unique_together': {('employee', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='skill_tags',
            field=models.ManyToManyField(blank=True, to='base.skill'),
        ),
        # Data migration skipped in squashed migration as it's not needed for fresh installs/tests.
        migrations.RemoveField(
            model_name='registration',
            name='skills',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='skill_tags',
            new_name='skills',
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=20)),
                ('profile_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='profile_score',
            field=models.IntegerField(default=0),
        ),
    ]
