# Generated by Django 5.2.7 on 2025-11-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
