# Generated by Django 5.2.7 on 2025-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_employer_registration_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
