# Generated by Django 5.2.7 on 2025-12-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_registration_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills (e.g., Excel, Tally, SAP, QuickBooks)', null=True),
        ),
    ]
