# Generated by Antigravity to fix missing table issue

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_registration_skills'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.CreateModel(
                    name='JobOpening',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.TextField()),
                        ('requirements', models.TextField()),
                        ('salary_range', models.CharField(blank=True, max_length=50)),
                        ('location', models.CharField(max_length=100)),
                        ('job_type', models.CharField(default='Full-time', max_length=50)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='base.employer')),
                    ],
                ),
            ],
            state_operations=[
                # The state for JobOpening was already applied in 0003 (which was faked)
                # So we don't need to add it to the state again.
            ]
        ),
    ]
