# Generated by Antigravity to fix potential password hash truncation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_repair_missing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
