# Generated by Django 5.2.7 on 2026-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_increase_password_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_placed',
            field=models.BooleanField(default=False, help_text='Mark this employee as placed (hired by an employer)'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
