# Generated by Django 5.2.7 on 2026-02-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_registration_is_placed_alter_employer_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='base.registration')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='base.employer')),
            ],
            options={
                'unique_together': {('employer', 'employee')},
            },
        ),
    ]
