# Generated by Django 5.2.7 on 2026-04-16 18:59

from django.db import migrations


def migrate_skills_to_m2m(apps, schema_editor):
    Registration = apps.get_model('base', 'Registration')
    Skill = apps.get_model('base', 'Skill')
    
    for emp in Registration.objects.all():
        if emp.skills:
            # Assume comma separated string
            skill_names = [s.strip() for s in emp.skills.split(',') if s.strip()]
            for name in skill_names:
                skill_obj, created = Skill.objects.get_or_create(name=name)
                emp.skill_tags.add(skill_obj)

def reverse_migrate_skills(apps, schema_editor):
    Registration = apps.get_model('base', 'Registration')
    
    for emp in Registration.objects.all():
        emp.skills = ", ".join(emp.skill_tags.values_list('name', flat=True))
        emp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_skill_registration_skill_tags'),
    ]

    operations = [
        migrations.RunPython(migrate_skills_to_m2m, reverse_migrate_skills),
    ]
