# Generated by Django 5.2.7 on 2026-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_migrate_skills_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='skills',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='skill_tags',
            new_name='skills',
        ),
    ]
