# Generated by Django 5.1.2 on 2026-04-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_useraccount_groups_useraccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_score',
            field=models.IntegerField(default=0),
        ),
    ]
