# Generated by Django 5.2.7 on 2026-04-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_squashed_0017_registration_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='profile_score',
        ),
    ]
