# Generated by Django 5.1.2 on 2026-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_registration_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='notice_period',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='profile_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
