# Generated by Django 5.1.2 on 2026-04-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_registration_notice_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='profile_score',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
