# Generated by Django 5.2.7 on 2026-04-21 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_registration_profile_score_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.registration')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
