# Generated by Django 5.2.7 on 2026-04-21 09:25

from django.db import migrations, models


def backfill_jobopening_skills_required(apps, schema_editor):
    JobOpening = apps.get_model('base', 'JobOpening')
    for job in JobOpening.objects.exclude(requirements='').filter(skills_required=''):
        job.skills_required = job.requirements
        job.save(update_fields=['skills_required'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_contactevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='skills_required',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='profile_score',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_jobopening_skills_required, noop_reverse),
    ]
