# Generated by Django 5.1.2 on 2026-04-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_employer_is_active_employer_subscription_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this candidate on the employer dashboard'),
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Application Submitted'), ('review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('contacted', 'Contacted')], default='submitted', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_status', to='base.registration')),
            ],
        ),
    ]
