# Generated by Django 5.1.2 on 2026-04-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_registration_is_featured_applicationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactevent',
            name='contact_type',
            field=models.CharField(default='whatsapp', max_length=20),
        ),
    ]
