# Generated by Django 5.1.2 on 2026-04-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_contactevent_contact_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='contactevent',
            options={'ordering': ['-contacted_at']},
        ),
        migrations.AlterModelOptions(
            name='employeeinterest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='employerinterest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobopening',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='applicationstatus',
            old_name='registration',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='applicationstatus',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='contactevent',
            old_name='timestamp',
            new_name='contacted_at',
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(choices=[('submitted', 'Application Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('contacted', 'Contacted')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactevent',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.registration'),
        ),
        migrations.AlterField(
            model_name='contactevent',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employer'),
        ),
        migrations.AlterField(
            model_name='employeeinterest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_interests', to='base.registration'),
        ),
        migrations.AlterField(
            model_name='employeeinterest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_interests', to='base.jobopening'),
        ),
        migrations.AlterField(
            model_name='employerinterest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='base.registration'),
        ),
        migrations.AlterField(
            model_name='employerinterest',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='base.employer'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_openings', to='base.employer'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='base.skill'),
        ),
    ]
