# Generated by Django 5.1.2 on 2026-04-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_applicationstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
    ]
