# Generated by Django 5.1.2 on 2026-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_password_fields_from_registration_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='subscription_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('premium', 'Premium')], db_index=True, default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_placed',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark this employee as placed (hired by an employer)'),
        ),
    ]
