# Generated by Django 5.1.2 on 2026-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_add_indexes_to_registration_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
